[tox]
envlist = flake8,py38,py39,py310


[testenv]
deps =
    coverage
    pytest
    pytest-cov
changedir = {envdir}
commands =
    {envbindir}/py.test --cov {envsitepackagesdir}/ploy/ --cov-report html:{toxinidir}/htmlcov_{envname} {posargs} {envsitepackagesdir}/ploy/


[testenv:flake8]
commands = flake8 --config {toxinidir}/.flake8 {toxinidir}/ploy {toxinidir}/ploy_pytest_plugin
deps = flake8
skip_install = true


[pytest]
addopts = --tb=native
